package com.example.scheduledreminder.model.enums;

import java.util.Collections;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public enum ApiResponseStatus {
    SUCCESS(1000, "Success"),
    ERROR_IN_REGISTRATION(1001, "Error In Registration"),
    MAIL_ALREADY_EXIST(1002, "E-mail already exists"),
    DATA_INVALID(1003, "Invalid Data"),
    INVALID_REFRESH_TOKEN(1010, "Invalid Refresh Token"),
    FAILURE(1011, "Failure"),
    ERROR_IN_LOGIN(1012, "Error in Login"),
    PASSWORD_VALIDATION_FAILED(1013, "Password Validation Failed"),
    USER_NOT_REGISTERED(1014, "User Not registered"),
    PASSWORD_NOT_SET(1015, "Password Not Set"),
    INVALID_MAIL_ID(1016, "Invalid Email-id"),
    INVALID_PHONE_NO(1017, "Invalid Phone No"),
    INVALID_USERNAME(1018, "Invalid Username a-z, 0-9, _, -, it must have 3-15 character"),
    PHONE_NO_EXIST(1019, "Phone No Exist"),
    USERNAME_NO(1020, "Username Already Exist"),
    USER_NOT_ENABLED(1021, "User not enabled"),
    INVALID_CREDENTIALS(1022, "Invalid Credentials"),
    RESET_TOKEN_INVALID(1023, "Password ResetToken is Invalid"),
    RESET_TOKEN_EXPIRED(1024, "Password ResetToken has Expired"),
    INVALID_ACCESS_TOKEN(1025, "INVALID_ACCESS_TOKEN"),

    INVALID_INSURANCE_WAIVER(1026, "Invalid WaiverAmount or WaiverPercentage"),
    INVALID_ADMIN_USER_ID(1027, "Invalid Admin User Id"),
    INVALID_REFERRAL_CODE(1028, "INVALID_REFERRAL_CODE"),
    APPOINTMENT_ALREADY_EXISTS(1029, "APPOINTMENT_ALREADY_EXISTS"),

    USER_ADD_ERROR(1201, "Error while adding user"),
    USER_UPDATE_ERROR(1202, "Error while updating user"),

    UNSPECIFIED_ERROR(5001, "Unspecified error"),


    ACCESS_INVALID(1301, "ACCESS_INVALID"),
    SYSTEM_PARAMETER_ADD_ERROR(1327, "SYSTEM_PARAMETER_ADD_ERROR"),
    SYSTEM_PARAMETER_UPDATE_ERROR(1328, "SYSTEM_PARAMETER_UPDATE_ERROR"),
    MAX_ALLOWED_BRANCHES_EXCEED(1329, "MAX_ALLOWED_BRANCHES_EXCEED"),
    MAX_ALLOWED_USERS_EXCEED(1330, "MAX_ALLOWED_USERS_EXCEED"),
    INVALID_USER_TYPE(1331, "INVALID_USER_TYPE"),

    HOSPITAL_NOT_ENABLED(1331, "HOSPITAL_NOT_ENABLED"),
    BRANCH_NOT_ENABLED(1331, "BRANCH_NOT_ENABLED"),

    USER_NOT_FOUND(1401, "USER NOT FOUND"),
    HOSPITAL_NOT_FOUND(1402, "HOSPITAL_NOT_FOUND"),
    BRANCH_NOT_FOUND(1403, "HOSPITAL_BRANCH_NOT_FOUND"),
    INVALID_SAVE_ADMIN_CONFIG_REQUEST(1404, "INVALID_SAVE_REQUEST"),
    CONFIG_NOT_FOUND(1405, "CONFIG_NOT_FOUND"),

    INSURANCE_NOT_FOUND(1406, "INSURANCE NOT FOUND"),
    MEDICINE_NOT_FOUND(1407, "MEDICINE_NOT_FOUND"),
    INJECTION_NOT_FOUND(1408, "INJECTION NOT FOUND"),

    INVALID_DOCTOR_ID(1409, "INVALID_DOCTOR_ID"),
    APPOINTMENT_NOT_FOUND(1410, "APPOINTMENT_NOT_FOUND"),

    INVALID_HOSPITAL_OR_BRANCH_CODE(1411, "INVALID_HOSPITAL_OR_BRANCH_CODE"),
    CONFIG_ID_ALREADY_EXIST(1412, "CONFIG_ID_ALREADY_EXISTS"),
    BREAKUP_CODE_NOT_FOUND(1413, "BREAKUP_CODE_NOT_FOUND"),
    CONFIG_ALREADY_EXIST(1414, "CONFIG_ALREADY_EXISTS"),
    INVALID_PATIENT_MRD_NUMBER(1415, "INVALID_PATIENT_MRD_NUMBER"),
    NO_BRANCH_FOUND_FOR_GIVEN_HOSPITAL_CODE(1416, "NO_BRANCH_FOUND_FOR_GIVEN_HOSPITAL_CODE"),
    DOCTOR_NOT_FOUND(1417, "DOCTOR_NOT_FOUND"),
    LAB_APPOINTMENT_NOT_FOUND(1418, "LAB_APPOINTMENT_NOT_FOUND"),
    SURGERY_APPOINTMENT_NOT_FOUND(1419, "SURGERY_APPOINTMENT_NOT_FOUND"),
    ATTACHMENT_NOT_FOUND(1420, "ATTACHMENT_NOT_FOUND"),
    LASER_APPOINTMENT_NOT_FOUND(1421, "LASER_APPOINTMENT_NOT_FOUND"),
    INJECTION_APPOINTMENT_NOT_FOUND(1422, "INJECTION_APPOINTMENT_NOT_FOUND"),
    WORKUP_APPOINTMENT_NOT_FOUND(1423, "WORKUP_APPOINTMENT_NOT_FOUND"),
    SOFTWARE_LICENSE_ALREADY_EXIST(1424, "SOFTWARE_LICENSE_ALREADY_EXIST"),
    MEDICAL_CAMP_NOT_FOUND(1425, "MEDICAL_CAMP_NOT_FOUND"),
    APPOINTMENT_MEDICAL_CAMP_NOT_FOUND(1426, "APPOINTMENT_MEDICAL_CAMP_NOT_FOUND"),

    CMS_CONFIG_NOT_FOUND(1501, "CMS_CONFIG_NOT_FOUND"),
    CMS_CONFIG_KEY_ALREADY_EXISTS(1502, "CMS_CONFIG_KEY_ALREADY_EXISTS"),
    KNOWLEDGE_BANK_TAG_ALREADY_EXISTS(1503, "KNOWLEDGE_BANK_TAG_ALREADY_EXISTS"),
    SYSTEM_PARAMETER_ALREADY_EXISTS(1504, "SYSTEM_PARAMETER_ALREADY_EXISTS"),
    SYSTEM_PARAMETER_NOT_FOUND(1505, "SYSTEM_PARAMETER_NOT_FOUND"),

    SYSTEM_PARAMETER_VALUE_MISMATCH(1601, "SYSTEM_PARAMETER_VALUE_MISMATCH"),
    ERROR_FETCHING_PINCODE(1602, "ERROR_FETCHING_PINCODE"),
    PAYMENT_ALREADY_DONE(1603, "PAYMENT_ALREADY_DONE"),
    APPOINTMENT_BOOKING_ALREADY_DONE(1604, "APPOINTMENT_BOOKING_ALREADY_DONE"),
    APPOINTMENT_ALREADY_CHECKED_IN(1605, "APPOINTMENT_ALREADY_CHECKED_IN"),
    PAYMENT_NOT_DONE(1606, "PAYMENT_NOT_DONE"),
    NO_SURGERIES_FOUND(1607, "NO_SURGERIES_FOUND"),
    NO_WORKUP_FOUND(1608, "NO_WORKUP_FOUND"),

    //Leave Error Status
    LEAVE_ALREADY_EXISTS_FOR_THE_GIVEN_TIME_RANGE(1701, "LEAVE_ALREADY_EXISTS_FOR_THE_GIVEN_TIME_RANGE"),

    INVALID_LEAVE_APPROVAL(1702, "INVALID_LEAVE_APPROVAL"),

    INVALID_SEARCH_FILTER(1703, "INVALID_SEARCH_FILTER"),

    //User App
    INVALID_USER_APP_TOKEN(1801, "INVALID_USER_APP_TOKEN"),
    OTP_ALREADY_SENT(1802, "OTP_ALREADY_SENT"),
    OTP_DOES_NOT_EXISTS_IN_SYSTEM(1803, "OTP_DOES_NOT_EXISTS_IN_SYSTEM"),

    //ABHA ERROR CODE

    ADHAR_OTP_REGISTRATION_FAILURE(1804, "ADHAR OTP CANNOT BE VALIDATED"),

    OTP_VERIFICATION_FAILURE(1805, "Wrong Otp provided for verification"),

    MOBILE_LINK_TO_ABHA_OTP_GENERATION_FAILURE(1806, "Mobile Link To Abha Otp Generation Failure"),

    ABHA_TO_PATIENT_REGISTRATION_FAILURE(1807, "Abha Patient Registration Failure"),

    ABHA_SESSION_FAILURE(1808, "Abha Session Failure"),


    // Sanjeevani Error
    PHARMACY_NOT_ENABLED(2101, "PHARMACY_NOT_ENABLED"),
    PHARMACY_NOT_FOUND(2102, "PHARMACY_NOT_FOUND"),
    PHARMACY_BRANCH_NOT_FOUND(2103, "PHARMACY_BRANCH_NOT_FOUND"),
    PHARMACY_BRANCH_NOT_ENABLED(2104, "PHARMACY_BRANCH_NOT_ENABLED"),
    MANUFACTURER_NOT_FOUND(2105, "MANUFACTURER_NOT_FOUND"),
    VENDOR_NOT_FOUND(2106, "VENDOR_NOT_FOUND"),
    MARKETED_BY_NOT_FOUND(2107, "MARKETED_BY_NOT_FOUND"),
    PRODUCT_NOT_FOUND(2108, "PRODUCT_NOT_FOUND"),
    ITEM_NOT_FOUND(2109, "ITEM_NOT_FOUND"),
    PROVIDE_MANDATORY_FIELDS(2110, "PROVIDE_MANDATORY_FIELDS"),
    INVENTORY_ITEM_NOT_FOUND(2111, "INVENTORY_ITEM_NOT_FOUND"),
    NEGATIVE_INVENTORY_ITEM_STOCK(2112, "NEGATIVE_INVENTORY_ITEM_STOCK"),
    ORDER_NOT_FOUND(2113, "ORDER_NOT_FOUND"),
    INVALID_QUANTITY_MODIFICATION(2114, "INVALID_QUANTITY_MODIFICATION");

    private static final Map<String, ApiResponseStatus> ENUM_MAP;

    static {
        Map<String, ApiResponseStatus> map = new ConcurrentHashMap<String, ApiResponseStatus>();
        for (ApiResponseStatus instance : ApiResponseStatus.values()) {
            map.put(String.valueOf(instance.getCode()), instance);
        }
        ENUM_MAP = Collections.unmodifiableMap(map);
    }

    private int code;
    private String message;

    ApiResponseStatus(int status, String message) {
        this.code = status;
        this.message = message;
    }

    public static ApiResponseStatus getInstance(String code) {
        return ENUM_MAP.get(code);
    }

    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
